version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo
steps:
  - checkout

  - restore_cache:
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

  - run: yarn install

  - run: yarn ci:cypress-run

  - save_cache:
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

  - run: yarn test
